version: '3.8'

services:
    php:
        build:
            context: '.'
            dockerfile: './docker/php/Dockerfile'
        ports:
            - 8000:80
            - 6001:6001
        restart: always
        volumes:
            -  ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./:/var/www/html:rw
            - ./docker/php/000-default.conf:/etc/apache2/sites-enabled/000-default.conf:ro
            - ./docker/php/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
            - ./docker/php/logs/:/var/log/apache2/:rw
        networks:
            - app-network

    database:
        image: mariadb
        restart: always
        ports:
            - 3306:3306
        volumes:
            - mysql:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - app-network
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 9080:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            - app-network
volumes:
    mysql:

networks:
    app-network:
        driver: bridge
